### PR TITLE
Provide instructions on how to use Registry mirrors in other regions

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by Djelibeybi** [comment]
I don't think we need to repeat the documentation three times. It's only necessary to have the detailed documentation in the `README.md` with links in `.env` and the `Vagrantfile` pointing back to that. This would make it easier to maintain over time.

Also note that it's not just the Region Key that can be used. The following are all valid aliases for a mirror:

* `container-registry-<region_name>.oracle.com`, e.g. `container-registry-sydney.oracle.com`
* `container-registry-<region_identifier>.oracle.com`, e.g. `container-registry-ap-sydney-1.oracle.com`
* `container-registry-<region_key>.oracle.com`, e.g. `container-registry-syd.oracle.com`

**Comment by rafabene** [comment]
Ok. Thanks @Djelibeybi . So I'll close this PR and open an issue. It's valid to have the regions documented somewhere.

**Comment by Djelibeybi** [comment]
You don't need to close this PR. I'm just asking you to adjust it. :)

**Comment by rafabene** [comment]
ok. I'll work on that later today.

**Comment by Djelibeybi** [comment]
For the `README.md` I would use language similar to this:

> For performance reasons, we recommend using the closest Oracle Container Registry mirror
to your region. A list of available regions can be found on the [Regions and Availability Domains](https://docs.cloud.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm) page of the Oracle Cloud Infrastructure documentation.

> To specify an Oracle Container Registry mirror, either edit the `Vagrantfile` or install the `vagrant-env` plugin and create a `.env.local` file that specifies the mirror. 

> The following syntax can be used to specify a mirror: `container-registry-<Region Key>.oracle.com`. For example, to use the mirror in Melbourne, specify `container-registry-mel.oracle.com` .

**Comment by rafabene** [comment]
Thanks @Djelibeybi . PR updated.

**Comment by Djelibeybi** [comment]
Nice. Merged!

**Pull request merged**
