### PR TITLE
Updating minimum resource requirements to allow Istio to start 

### LINKED ISSUE #237: OLCNE default resources are insufficient for Istio
OLCNE with 2 worker nodes is not enough to run all pods of Istio. When observing the pods, some of them are in the `Pending` state and the cause is:

>Warning  FailedScheduling  2m11s (x2 over 2m11s)  default-scheduler  0/3 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 2 Insufficient memory.
  Warning  FailedScheduling  55s (x2 over 55s)      default-scheduler  0/3 nodes are available: 1 Insufficient cpu, 1 Insufficient memory, 1 node(s) had taints that the pod didn't tolerate.

Some possible solutions:
- Set the minimum number of Worker Nodes as 3 if ISTIO variable is true
- Document the minimum number of worker node for Istio
- Remove the taint of master
- Increase the vCPUs to 3 by default

### PR DESCRIPTION
**Pull request by Djelibeybi**
his is still significantly less than the documented requirements for master and worker nodes. I also fixed the formatting of the `README.md` to pass the Markdownlint tests.

Resolves #237. 

Signed-off-by: Avi Miller <avi.miller@oracle.com>

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Fair call. Though, we need to acknowledge that the resource requirements are cumulative. Keep in mind that the documented minimums are supposed to be 16GB for the master and 8GB per worker, so this is still significantly less than what we document.

**Comment by rafabene** [comment]
Plus, I'd like to bring to the discussion the fact that **IF** the purpose of this Vagrantfiles is to allow **developers** to use the environment for dev purposes, some features should be disabled like *"zero-impact upgrade process"* (single replica for Istio pods) and taint removed from master (to reduce the number of VMs. **IF** this OLCNE Vagrantfile is not for **Devs**, but **for Admins** to test OLCNE capabilities without having to install it, it makes total sense to keep it the way it is. In that case I'll propose a new Vangratfile for **developers** to use OLCNE. (Something lightweight like minikube)

**Comment by Djelibeybi** [comment]
In my head, the purpose of the Vagrant files is to "kick the tyres" of Oracle products, i.e. to see what functionality they provide out-of-the-box but in a smaller environment that can't actually support production workloads. As such, the fact that Istio is HA by default is something that needs to be demonstrated (it's a feature).

I don't consider these Vagrant boxes useful for the developer use-case because that's not how they've been designed. OLCNE itself is not designed as a "single box" solution at all.

However, I also understand the scale of these things and I know requiring 15GB for the smallest possible install is unfeasible. 

These are all good points. We'll need to end up somewhere in the middle. What I really want to try and avoid though is hacking the product for our purposes. That's not a sustainable model downstream. I want to limit our choices to tunables that are presented by the product specifically.

**Comment by Djelibeybi** [comment]
Closing this as unfeasible. The requirements are too high. We need to reconsider how to offer OLCNE in a more resource-frendly way.

**Pull request closed without merging**
