### PR TITLE
Allow configuration of Database 12.2.0.1 box time zone (#33)

### PR DESCRIPTION
**Pull request by PaulNeumann**
This implements the enhancement in Issue #33. By default, the VM time zone is set to the host time zone when the host time zone is an integer hour offset from GMT. When the host time zone is **not** an integer hour offset (e.g., in India), the VM time zone is set to UTC. In either case, a different time zone can be specified either by name (e.g., "America/Los_Angeles") or by an offset from GMT (e.g., "Etc/GMT-2") in the environment section of the `Vagrantfile`.

Changes are:
- In the `Vagrantfile`, add code to determine host time zone. If the host time zone isn't an integer hour offset from GMT, then default to UTC.
- In the `Vagrantfile`, add a variable in the environment section to pass the time zone to `install.sh`
- In `install.sh`, add code to set the VM's time zone using the environment variable passed in from the `Vagrantfile`
- Update `README.md` to describe the new functionality

To validate (destroy the box between tests):
1. Test `Vagrantfile` default (host time zone, whenever possible, or UTC)
    1. Run `vagrant up`. After the box is provisioned, ssh to it and run the `timedatectl` command. If the host time zone is an integer hour offset from GMT, the time zone shown should match the host time zone. If the host time zone is **not** an integer hour offset (e.g., in India), the time zone shown should be UTC.

2. Test using time zone name
    1. Modify the `SYSTEM_TIMEZONE` variable in the env section of the `Vagrantfile` to use a time zone name, e.g., `"SYSTEM_TIMEZONE" => "America/Chicago"`.
    2. Run `vagrant up`. After the box is provisioned, ssh to it and run the `timedatectl` command. The time zone shown should match the time zone specified in the `Vagrantfile`.

3. Test using offset from GMT
    1. Modify the `SYSTEM_TIMEZONE` variable in the env section of the `Vagrantfile` to use an offset from GMT, e.g., `"SYSTEM_TIMEZONE" => "Etc/GMT-6"`.
    2. Run `vagrant up`. After the box is provisioned, ssh to it and run the `timedatectl` command. The time zone shown should match the time zone specified in the `Vagrantfile`.

(For each of these scenarios, one can also connect to the database and run the query `SELECT SYSTIMESTAMP FROM DUAL;`. The date and time returned should match the VM time zone.)

Signed-off-by: Paul Neumann <38871902+PaulNeumann@users.noreply.github.com>

### CODE REVIEW

**Comment by gvenzl** [comment]
Just tested and works great!

Two requests though before we merge this:

* Can you please also add this change for the 18c and 11g Vagrantfiles so that we stay consistent?
* Please link to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones in the ReadMe for folks who don't know Linux timezones well.

**Comment by PaulNeumann** [comment]
Thank you, sir. I've made the requested changes and tested them in my environment.

I hope I've captured what you want with the README.md files. If not, I'm happy to revise them.

(There are 2 new commits. The first is a merge commit, which was needed to add the 18c box to my branch. I originally created the branch before you released the 18c box. The second commit includes the changes you requested.)

**Comment by gvenzl** [comment]
Thank you very, very much for this great contribution, @PaulNeumann!

**Comment by PaulNeumann** [comment]
You're welcome, and thank you! I use these boxes daily. They save me a ton of time, and I learn a lot from working with them, so I'm happy to give back when I can.

**Comment by PaulNeumann** [comment]
@totalamateurhour You can email me at paulneumann1 at gmail.com.

**Comment by AmedeeBulle** [comment]
Deleted previous comments for privacy reason 
@PaulNeumann we have your information - thanks

**Pull request merged**
