### PR TITLE
Introducing OL8 box

### LINKED ISSUE #186: Add OL 8 Vagrantfile
The Vagrantfile for OL 8 is missing in GitHub though the box is available for download (https://yum.oracle.com/boxes).

### PR DESCRIPTION
**Pull request by gvenzl**
This fixes #186 

Signed-off-by: Gerald Venzl <gerald.venzl@oracle.com>

### CODE REVIEW

**Comment by PaulNeumann** [comment]
Nice!

Suggestion: It might make sense to change line 17 of `install.sh` to `dnf upgrade -y`, since DNF is preferred for OL8. (`yum` is really symlinked to `dnf` anyway.)

Also, there are a couple of issues with the current (07-Oct-2019) version of the ol8-latest base box that people will probably run into:

* The base box is missing 3 packages (elfutils-libelf-devel, gcc and kernel-devel) that are required to rebuild the VirtualBox Guest Additions after a kernel upgrade. Without them, the GAs (including shared folders) will stop working after a kernel upgrade when the VM is rebooted. (And building this box will upgrade the kernel and reboot.)

* Even after installing the missing packages, there's a dracut error anytime the kernel is upgraded or the GA kernel modules are rebuilt:
  ```
    dracut-install: ERROR: installing 'virtio'
    dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.TxRUbT/initramfs -N floppy --kerneldir /lib/modules/4.18.0-80.11.2.el8_0.x86_64/ -m xen_netfront xen_blkfront virtio_blk virtio_net virtio virtio_pci virtio_balloon hyperv_keyboard hv_netvsc hid_hyperv hv_utils hv_storvsc hyperv_fb ahci libahci mptspi
  ```
  I don't know what causes this, but it doesn't seem to affect the functionality of the VM.

**Comment by gvenzl** [comment]
If `dnf` is the default on OL8, then we definitely should change it. Part of these scripts is also to provide a reference implementation/examples for users. I.e. Oracle provides Oracle Linux, then we should also be the first ones to adopt our new features. :)

**Comment by AmedeeBulle** [comment]
While I don't disagree, on OL8 `dnf`and `yum` are pointing to same executable, so it does not matter too much...
But good to stat to have `dnf` in the fingers

```
[opc@ol8 ~]$ ls -l /usr/bin/{dnf,yum}
lrwxrwxrwx. 1 root root 5 May 23  2019 /usr/bin/dnf -> dnf-3
lrwxrwxrwx. 1 root root 5 May 23  2019 /usr/bin/yum -> dnf-3
```

**Comment by fribeiro1** [comment]
Thanks!

**Comment by Djelibeybi** [comment]
> While I don't disagree, on OL8 `dnf`and `yum` are pointing to same executable, so it does not matter too much...

It matters from a best practice perspective and the fact that there is no guarantee that `yum` will continue to be symlinked as it is now. Also, the Docker images may or may not have yum at all and the `8-slim` image doesn't even have `dnf` (it uses `microdnf`). So getting folks used to the new normal is a good thing.

**Pull request merged**
