### PR TITLE
No click-through XE

### PR DESCRIPTION
**Pull request by gvenzl**
Signed-off-by: Gerald Venzl <gerald.venzl@oracle.com>

### CODE REVIEW

**Comment by PaulNeumann** [comment]
@gvenzl This is really great!

May I make a suggestion? It might be good to save the rpm, so that people don't have to download it every time they build the box. A 2.3 GB download can be problematic for those with low-bandwidth or metered connections. Replacing line 51 of `install.sh` with something like the following would provide the best of both worlds, and it wouldn't require any changes to `README.md`:

```shell
if [[ ! -f /vagrant/oracle-database-xe-18c-1.0-1.x86_64.rpm ]]; then
  echo 'INSTALLER: Downloading Oracle Database software'
  wget -q -P /vagrant \
    https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm
fi
yum -y localinstall /vagrant/oracle-database-xe-18c-1.0-1.x86_64.rpm
```

**Comment by Djelibeybi** [comment]
I like the suggestion, but would suggest wrap it in a conditional, as other people may not like a 2.3GB RPM just cluttering up their drive. :)

**Comment by PaulNeumann** [comment]
@Djelibeybi Very true, but that was how it worked before, and it's also how the other boxes in this repo work. (And `*.rpm` is already in `.gitignore`, so it'd be "safe".)

**Comment by PaulNeumann** [comment]
@Djelibeybi My comment above was both rude and wrong. I'm sorry.

Providing a choice to keep or discard the rpm is a good idea. One way to implement it might be to add a parameter in the env section of the Vagrantfile (e.g., `KEEP_INSTALLER => "YES"`). Then, in `install.sh`, the following could be added after the snippet above:

```shell
if [[ "${KEEP_INSTALLER}" != 'YES' ]]; then
  rm /vagrant/oracle-database-xe-18c-1.0-1.x86_64.rpm
fi
```

**Comment by Djelibeybi** [comment]
> @Djelibeybi My comment above was both rude and wrong. I'm sorry.

I found it to be neither, but as someone who has been both in the past, thank you for saying so. And I like your solution too.

**Pull request merged**
