### PR TITLE
Abort install on any error

### PR DESCRIPTION
**Pull request by gvenzl**
Fix for #160 
Signed-off-by: Gerald Venzl <gerald.venzl@oracle.com>

### CODE REVIEW

**Comment by PaulNeumann** [comment]
@gvenzl
Great idea! It might also make sense to remove all of the && lists from the install.sh scripts, so that the scripts abort immediately after the first failed command. From the bash documentation for `set -e` at  [http://man7.org/linux/man-pages/man1/bash.1.html](http://man7.org/linux/man-pages/man1/bash.1.html) (emphasis added):
> The shell does not exit if the command that fails is part of the command list immediately following a while or until keyword, part of the test following the if or elif reserved words, **part of any command executed in a && or || list** except the command following the final && or || ...

For example, in #159, the 11g XE install.sh script was run when the installer zip wasn't present. In this same scenario with `set -e` added to the script, the last part of the output is:
```
    oracle11g-xe-vagrant: INSTALLER: Locale set
    oracle11g-xe-vagrant: INSTALLER: System time zone set to Etc/GMT+7
    oracle11g-xe-vagrant: INSTALLER: Oracle directories created
    oracle11g-xe-vagrant: unzip:  cannot find or open /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip, /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip.zip or /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip.ZIP.
    oracle11g-xe-vagrant: INSTALLER: Oracle software installed
    oracle11g-xe-vagrant: sudo
    oracle11g-xe-vagrant: :
    oracle11g-xe-vagrant: /etc/init.d/oracle-xe: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
So the script does abort, but not immediately after the failed unzip, because the unzip is part of a && list. Removing all instances of ` && \` from the install.sh scripts would let `set -e` work as intended.

**Comment by mark-au** [comment]
@PaulNeumann that's a good point but instead of removing `&&` usage we can enable the bash option `-o pipefail`
What do you think @gvenzl ?

**Comment by PaulNeumann** [comment]
@mark-au Thanks! Do the && lists still add value with `set -e` enabled, though? It doesn't seem like it to me, but I'm not a bash guru, and I could be missing something.

**Comment by mark-au** [comment]
I don't think they add value but expect these scripts were written for cross-use in the creation of container images where they certainly add value

**Comment by PaulNeumann** [comment]
Again, thanks! I appreciate your insight.

When I add `set -e -o pipefail` (or `set -eo pipefail`) to the 11g XE script and run it with the zip file missing, I get the same result I posted above, i.e., the script aborts when it tries to run `/etc/init.d/oracle-xe`, not immediately after the failed unzip. Perhaps that's good enough, or perhaps there's another way to get this to work while retaining the && lists.

**Comment by gvenzl** [comment]
Indeed the scripts came over from the container images world where they added value by only running in one and not many layers.
Here, on the other hand, that offers little benefit and the scripts by now have deviated far enough (with Docker multistage builds) that we don't need to keep them in sync anymore. Therefore I agree that the right approach should be to remove the `&&` and let the actual command fail and abort the build, rather than as even with `-o pipefail` have the last command in the pipe report the error.

**Comment by PaulNeumann** [comment]
@gvenzl If it would be helpful, I could submit a PR to remove the `&&` lists from the `install.sh` scripts per the discussion above.

**Pull request merged**
